name: "build-aon"
on:
  # Trigger the workflow on push or pull request,
  # but only for the main branch
  push: 
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-aon:
    needs: build-aon
    strategy:
      matrix:
        # os: [ubuntu-22.04, macos-latest, macos-13]
        os: [ubuntu-22.04]

    runs-on: ${{ matrix.os }}
    steps:
      - run: sudo apt-get install -y qemu-user-static

      - uses: actions/checkout@v3

      - name: Extend space
        if: ${{ matrix.os == 'ubuntu-latest' }}
        uses: ./.github/actions/extend-space

      - name: Install nix
        uses: cachix/install-nix-action@v27
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}
          nix_path: nixpkgs=channel:nixos-24.05
          extra_nix_config: |
            system = aarch64-linux

      - uses: cachix/cachix-action@v15
        with:
          name: holochain-ci

      - uses: cachix/cachix-action@v15
        with:
          name: darksoil-studio

      - name: Build rpi-aon
        env:
          CACHIX_AUTH_TOKEN: "${{ secrets.DARKSOIL_CACHIX_AUTH_TOKEN }}"
        run: |
          cachix watch-exec darksoil-studio -- nix build -L --accept-flake-config --no-update-lock-file .#rpi-aon

      - name: 'Setup jq'
        uses: dcarbone/install-jq-action@v2

      - name: Pin rpi-aon
        if: github.event_name != 'pull_request'
        env:
          CACHIX_AUTH_TOKEN: "${{ secrets.DARKSOIL_CACHIX_AUTH_TOKEN }}"
        run: |
          cachix pin darksoil-studio rpi-aon $(nix path-info --json --accept-flake-config --no-warn-dirty .#rpi-aon | jq -r 'keys[0]')
